/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package statmedx1;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import statmedx1.DatabaseConnection;
import static statmedx1.Filter.EEfilter;

/**
 *
 * @author signekristiansen
 */
public class FilterFrameold extends javax.swing.JFrame {
    private boolean Nofilter = false;
    private boolean EEfilter = false;
    private boolean RQfilter = false;
    private boolean FiO2filter = false;
    private boolean PEEPfilter = false;

    /**
     * Creates new form FilterFrame
     */
    public FilterFrameold() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        No_filter = new javax.swing.JCheckBox();
        EE_filter = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        RQ_filter = new javax.swing.JCheckBox();
        PEEP_filter = new javax.swing.JCheckBox();
        FiO2_filter = new javax.swing.JCheckBox();
        apply_filters = new javax.swing.JButton();
        RQ_lower = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RQ_upper = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PEEP_lower = new javax.swing.JTextField();
        FIO2_lower = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EE_lower = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        No_filter.setAction(No_filter.getAction());
        No_filter.setText("No filters");
        No_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_filterActionPerformed(evt);
            }
        });

        EE_filter.setAction(EE_filter.getAction());
        EE_filter.setText("EE filter");
        EE_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EE_filterActionPerformed(evt);
            }
        });

        jButton1.setText("StatMedX");

        jButton2.setText("Chose how to filter the data");

        RQ_filter.setText("RQ filter");
        RQ_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RQ_filterActionPerformed(evt);
            }
        });

        PEEP_filter.setText("PEEP filter");
        PEEP_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PEEP_filterActionPerformed(evt);
            }
        });

        FiO2_filter.setText("FiO2 filter");
        FiO2_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiO2_filterActionPerformed(evt);
            }
        });

        apply_filters.setText("Apply filters");
        apply_filters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apply_filtersActionPerformed(evt);
            }
        });

        RQ_lower.setText("0.7");

        jLabel1.setText("kcal/day");

        jLabel2.setText("Chose lower level for RQ");

        jLabel3.setText("Chose lower level for energy expenditure");

        jLabel4.setText("Chose upper level for RQ");

        RQ_upper.setText("1.0");

        jLabel5.setText("Chose upper level for FiO2");

        PEEP_lower.setText("10");

        FIO2_lower.setText("0.6");

        jLabel6.setText("Chose upper level for PEEP");

        jLabel7.setText("cmH2O");

        EE_lower.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(PEEP_lower, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(No_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FiO2_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PEEP_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RQ_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RQ_lower, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RQ_upper, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(FIO2_lower)
                                .addGap(316, 316, 316))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EE_filter)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EE_lower, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(apply_filters, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(No_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EE_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EE_lower, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RQ_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RQ_lower, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RQ_upper, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FiO2_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FIO2_lower, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PEEP_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PEEP_lower, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(apply_filters)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void No_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_filterActionPerformed
        // TODO add your handling code here:
        
        if(No_filter.isSelected()){
            Nofilter = true;
        }
        else{
            Nofilter = false;
        }
    }//GEN-LAST:event_No_filterActionPerformed

    private void EE_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EE_filterActionPerformed
        // TODO add your handling code here:
          if(EE_filter.isSelected()){
            EEfilter = true;
        }
        else{
            EEfilter = false;
        }
    }//GEN-LAST:event_EE_filterActionPerformed

    private void PEEP_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PEEP_filterActionPerformed
        // TODO add your handling code here:
          if(PEEP_filter.isSelected()){
            PEEPfilter = true;
        }
        else{
            PEEPfilter = false;
        }
    }//GEN-LAST:event_PEEP_filterActionPerformed

    private void RQ_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RQ_filterActionPerformed
        // TODO add your handling code here:
          if(RQ_filter.isSelected()){
            RQfilter = true;
        }
        else{
            RQfilter = false;
        }
    }//GEN-LAST:event_RQ_filterActionPerformed

    private void FiO2_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiO2_filterActionPerformed
        // TODO add your handling code here:
          if(FiO2_filter.isSelected()){
            FiO2filter = true;
        }
        else{
            FiO2filter = false;
        }
    }//GEN-LAST:event_FiO2_filterActionPerformed

    private void apply_filtersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apply_filtersActionPerformed
        // TODO add your handling code here:
       
//        try{
//        Connection connection;
//        connection = DatabaseConnection.getConnection();
        if(Nofilter == false && EEfilter==false && RQfilter==false && FiO2filter==false && PEEPfilter==false){
            String message = "Please choose a filter before continuing";
            JOptionPane.showMessageDialog(this, message);
        }
        else if(Nofilter == true){
           System.out.println("Select all data");
          
        }
        // EE filter
        else if(EEfilter ==true){
            if(RQfilter == false && PEEPfilter == false && FiO2filter == false){
           //System.out.println("Only use EE filter");
           int filterValue = Integer.parseInt(EE_lower.getText()); // Get the value entered by the user   
           String sqlQuery = "SELECT EE FROM TABLE16 WHERE EE > ? "; // Set the SQL query to execute
           List<String> filteredValues = Filter.EEfilter(sqlQuery, filterValue); // Call the EEfilter() method with the SQL query and the user's input as parameters
           String message = "Filtered values:\n" + String.join("\n", filteredValues); // Create a message with the filtered values
           JOptionPane.showMessageDialog(this, message); // Display the message in a dialog box
         
            }
            
            else if(RQfilter == true && PEEPfilter == false && FiO2filter == false){
              System.out.println("Use EE filter and RQ filter");  
            }
            
            else if(RQfilter ==true){
            if(EEfilter == false && PEEPfilter == false && FiO2filter == false){
           //System.out.println("Only use EE filter");
           int filterValue = Integer.parseInt(RQ_lower.getText()); // Get the value entered by the user   
           String sqlQuery = "SELECT EE FROM TABLE16 WHERE RQ > ? "; // Set the SQL query to execute
           List<String> filteredValues = Filter.EEfilter(sqlQuery, filterValue); // Call the EEfilter() method with the SQL query and the user's input as parameters
           String message = "Filtered values:\n" + String.join("\n", filteredValues); // Create a message with the filtered values
           JOptionPane.showMessageDialog(this, message); // Display the message in a dialog box
         
            }
            }
            
           
            
        }
       
        
        
//        else if(EEfilter == true && Nofilter == false){
//        List<String> filteredValues = EEfilter();
//        System.out.println(filteredValues);
//        }
        
        
//       catch (HeadlessException e) {
//            JOptionPane.showMessageDialog(null,e);
//        } catch (SQLException ex) {
//            Logger.getLogger(FilterFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        

    }//GEN-LAST:event_apply_filtersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilterFrameold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilterFrameold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilterFrameold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilterFrameold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilterFrameold().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox EE_filter;
    private javax.swing.JTextField EE_lower;
    private javax.swing.JTextField FIO2_lower;
    private javax.swing.JCheckBox FiO2_filter;
    private javax.swing.JCheckBox No_filter;
    private javax.swing.JCheckBox PEEP_filter;
    private javax.swing.JTextField PEEP_lower;
    private javax.swing.JCheckBox RQ_filter;
    private javax.swing.JTextField RQ_lower;
    private javax.swing.JTextField RQ_upper;
    private javax.swing.JButton apply_filters;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
